server:
  port: 8002

spring:
  application:
    name: hotel-service
    description: guest service for my hotel application
    version: @project.version@

  datasource:
    url: jdbc:mysql://localhost:3306/myhotel
    username : root
    password : root
  jpa:
    hibernate :
      ddl-auto : create
      show-sql : true
