spring:
  application:
    name: hotel-service

  h2:
    console :
      enabled : true
      path : /h2

  datasource:
    url: jdbc:h2:mem:testdb

  data:
    jpa:
      repositories:
        bootstrap-mode: default


server:
  port: 8031

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8383/eureka/
  instance:
    hostname: localhost